version: '3.2'

services:
   db:
      image: mysql:5.6.46
      container_name: analyticDB
      restart: always
      volumes:
       - ./SRC/DockerSubSystems/mysql:/var/lib/mysql
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: admin
      networks:
         testing_net:
            ipv4_address: 172.26.0.2

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
      networks:
         testing_net:
            ipv4_address: 172.26.0.3

   node-red:
      depends_on:
         - db
      image: nodered/node-red:latest
      restart: always
      environment:
         - TZ=Europe/Amsterdam
      ports:
         - "1880:1880"
      volumes:
         - ./SRC/DockerSubSystems/node-red-data:/data
      networks:
         testing_net:
            ipv4_address: 172.26.0.4

networks:
   testing_net:
         ipam:
            driver: default
            config:
               - subnet: 172.26.0.0/24
                 gateway: 172.26.0.1

