version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: analyticDB
      restart: always
      volumes:
       - ./SRC/DockerSubSystems/mysql:/var/lib/mysql
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: admin

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db

   node-red:
      depends_on:
         - db
      image: nodered/node-red:latest
      restart: always
      environment:
         - TZ=Europe/Amsterdam
      ports:
         - "1880:1880"
      volumes:
         - ./SRC/DockerSubSystems/node-red-data:/data

